---
- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Copy hello world .html file
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html
  notify: restart nginx
